USE AEC;

CREATE TABLE Candidate
(
	CandidateId INT IDENTITY(10001, 1) PRIMARY KEY,
	SSN VARCHAR(11) NOT NULL,
	HomeAddress NVARCHAR(100) NOT NULL,
	ContactInfoId INT FOREIGN KEY REFERENCES ContactInfo(ContactInfoId),

	CONSTRAINT CHECK_Candidate_SSN CHECK(SSN LIKE '___-__-____')
);

GO;