USE AEC;

CREATE TABLE Company
(
	CompanyId INT IDENTITY(10001, 1) PRIMARY KEY,
	[Name] NVARCHAR(15) NOT NULL,
	[Address] NVARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL,
	ContactName NVARCHAR(45) NOT NULL,

	CONSTRAINT CHECK_Company_PhoneNumber CHECK (PhoneNumber LIKE '+% %-%-%')
);